package com.vidya.core.ai.models

/**
 * Defines how Gemma 4 should structure its response according to the Curriculum Graph.
 */
enum class PedagogyMode {
    VISUAL_MATH,
    PREDICT_EXPLAIN,
    STORY_NARRATE,
    LANG_DRILL
}

/**
 * Represents a discrete, fine-grained concept loaded from the local Curriculum Graph SQLite DB.
 */
data class ActiveConcept(
    val code: String,
    val name: String,
    val pedagogyMode: PedagogyMode,
    val difficulty: Int
)

/**
 * Represents the current state of the active teaching session.
 */
data class SessionState(
    val classGrade: Int, // e.g., 6 or 10
    val subject: String, // e.g., "Science", "Mathematics"
    val chapter: String, // e.g., "Components of Food"
    val activeConcept: ActiveConcept, // Maps directly to the Prisma schema's Concept node
    val targetLanguage: String = "en" // e.g., "hi" for Hindi, "ta" for Tamil
)

/**
 * Classification of the student's spoken input.
 */
enum class IntentType {
    DIRECT_QUESTION,
    DOUBT_CONFUSION,
    FOLLOW_UP
}

/**
 * The output of the Intent Classification step.
 */
data class ClassifiedIntent(
    val type: IntentType,
    val expandedSearchQuery: String, // Cleaned up query for the PhD database search (in English for DB)
    val detectedLanguage: String // The language the student actually spoke in
)

/**
 * Represents a chunk of expert knowledge retrieved from the ObjectBox Vector DB.
 */
data class KnowledgeChunk(
    val id: String,
    val text: String,
    val metadata: ChunkMetadata,
    val isExpert: Boolean // True if from PhD data, false if from textbook
)

data class ChunkMetadata(
    val subject: String,
    val gradeMin: Int,
    val gradeMax: Int,
    val complexity: Float,
    val source: String
)

/**
 * The final output generated by the AI to be spoken and displayed.
 */
data class AiResponse(
    val audioText: String, // Simplified response to be spoken aloud
    val screenText: String, // Detailed response for the teacher's screen
    val suggestedNomination: String?, // e.g., "Ask a student from the back row"
    val bridgeQuestion: String // The Socratic follow-up or check for understanding
)

/**
 * Represents a single exchange in the conversation history.
 */
data class Exchange(
    val studentInput: String,
    val aiResponse: AiResponse,
    val timestamp: Long = System.currentTimeMillis()
)
